# This exposes a fan entity to the frontend (like Home Assistant).
---
substitutions:
  fan_name: "SkyFan DC Fan"

fan:
  - id: skyfan
    platform: tuya
    speed_datapoint: 3
    switch_datapoint: 1
    direction_datapoint: 8
    name: ${fan_name}
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    speed_count: 5
  
select:
  - id: datapoint_mode
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Mode
    enum_datapoint: 2
    options:
      0: NORMAL
      1: ECO
      2: SLEEP
    disabled_by_default: true

  - id: datapoint_timer
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Timer
    enum_datapoint: 22
    options:
      0: NIL
      1: 1_HOUR
      2: 2_HOUR
      3: 3_HOUR
      4: 4_HOUR
      5: 5_HOUR
      6: 6_HOUR
      7: 7_HOUR
      8: 8_HOUR
      9: 9_HOUR
      10: 10_HOUR
      11: 11_HOUR
      12: 12_HOUR
    disabled_by_default: true
