# This exposes a light entity to the frontend (like Home Assistant). 
# Tuya datapoints thanks of https://github.com/SirMrDexter/skyfandc
#
# **WARNING**
# Untested.
---
substitutions:
  light_name: "SkyFan DC Light"

light:
  - id: skyfan_light
    platform: tuya
    name: ${light_name}
    switch_datapoint: 15
    dimmer_datapoint: 16
    min_value: 0
    max_value: 5
    color_temperature_datapoint: 19
    color_temperature_max_value: 2
    color_temperature_invert: true
    cold_white_color_temperature: 6500
    warm_white_color_temperature: 3000
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
